<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_startup_check_exce2a8a81d294d367a07fcb941ca1614ae5" kind="class" language="Python" prot="public">
    <compoundname>NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::StartupCheckException::StartupCheckException</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_startup_check_exce2a8a81d294d367a07fcb941ca1614ae5_1a39cbd39c3a77f3acc9c3feb3bfb84d7e" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.StartupCheckException.StartupCheckException.__init__</definition>
        <argsstring>(self, message=&quot;&quot;, errors=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>message</type>
          <defname>message</defname>
          <defval>&quot;&quot;</defval>
        </param>
        <param>
          <type>errors</type>
          <defname>errors</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="NEAT/ErrorHandling/Exceptions/StartupCheckException.py" line="2" column="1" bodyfile="NEAT/ErrorHandling/Exceptions/StartupCheckException.py" bodystart="2" bodyend="3"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="194">
        <label>Exception</label>
      </node>
      <node id="193">
        <label>NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.StartupCheckException.StartupCheckException</label>
        <link refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_startup_check_exce2a8a81d294d367a07fcb941ca1614ae5"/>
        <childnode refid="194" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="196">
        <label>Exception</label>
      </node>
      <node id="195">
        <label>NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.StartupCheckException.StartupCheckException</label>
        <link refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_startup_check_exce2a8a81d294d367a07fcb941ca1614ae5"/>
        <childnode refid="196" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="NEAT/ErrorHandling/Exceptions/StartupCheckException.py" line="1" column="1" bodyfile="NEAT/ErrorHandling/Exceptions/StartupCheckException.py" bodystart="1" bodyend="3"/>
    <listofallmembers>
      <member refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_startup_check_exce2a8a81d294d367a07fcb941ca1614ae5_1a39cbd39c3a77f3acc9c3feb3bfb84d7e" prot="public" virt="non-virtual"><scope>NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::StartupCheckException::StartupCheckException</scope><name>__init__</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
