<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="dir_0a11ab0822cd8a91fbd2d536d6edd3c0" kind="dir">
    <compoundname>NEAT/ErrorHandling/Exceptions</compoundname>
    <innerfile refid="_error_handling_2_exceptions_2____init_____8py">__init__.py</innerfile>
    <innerfile refid="_input_missing_exception_8py">InputMissingException.py</innerfile>
    <innerfile refid="_network_protocol_exception_8py">NetworkProtocolException.py</innerfile>
    <innerfile refid="_network_timeout_exception_8py">NetworkTimeoutException.py</innerfile>
    <innerfile refid="_serialization_exception_8py">SerializationException.py</innerfile>
    <innerfile refid="_socket_already_used_exception_8py">SocketAlreadyUsedException.py</innerfile>
    <innerfile refid="_socket_runtime_exception_8py">SocketRuntimeException.py</innerfile>
    <innerfile refid="_startup_check_exception_8py">StartupCheckException.py</innerfile>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <location file="NEAT/ErrorHandling/Exceptions/"/>
  </compounddef>
</doxygen>
